name: 'ga4'
version: '3.2.1'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
vars: 
    project: "gen-dw-prod" 
    property_ids: [335772514, 335774252, 336890609, 337039321, 337262399]
    static_incremental_days: 3
    dataset: "osaka_ga4_combined"
models:
  ga4:
    +materialized: view
    marts:
      +materialized: table
